### PR TITLE
Add Back button to Watch page (WIP)

### PR DESCRIPTION
**Pull request by alexliebowitz**
Code is basically done, but not mergeable yet because it includes code to imitate Job's new HTML5 player on the Electron branch.

### CODE REVIEW

**Comment by kauffj** [comment]
@jobevers This is ready to go, but contains a change to make the player HTML5 only. Perhaps this should be against a different branch specific to Electron?

Either way, this shouldn't be merged until the UI is being used by Electron, but is ready.

**Comment by alexliebowitz** [comment]
I based this on development just because I didn't have a working Electron installation at the time. I haven't tried it on Electron yet and it will require some small adjustments to work (e.g. right now the overlay is always present, but it should really only show up at the same time as the video controls).

I'll get this up to date against the Electron branch and ready to go soon.

**Comment by jobevers** [comment]
`I'll get this up to date against the Electron branch and ready to go soon.`

Ping me when thats up and I'll take a look

**Comment by jobevers** [comment]
what is the status on this?

**Comment by kauffj** [comment]
I'm merging this. Thank you for splitting the CSS into files. Possibly worth splitting the video player into it's own component, but definitely not worth blocking over.

**Pull request merged**
