### PR TITLE
Convert to ES6 Modules

### PR DESCRIPTION
**Pull request by jobevers**
- Adds imports and exports to each file (no more global state!)
 - builds and bundles the app using webpack
 - adds eslint (but only one check is turned on)

Webpack has a nice hot-reloading server that can be run like:
`webpack-dev-server --progress --colors --port=5280 --content-base=dist`

Until this PR gets merged, https://github.com/lbryio/lbry/pull/286, you'll run into CORS issues
but after that PR, you can launch the daemon like:
`LBRY_ALLOWED_ORIGIN=http://localhost:5280 lbrynet-daemon --log-to-console --no-launch`

And the UI will be able to talk to the daemon, and will automatically rebuild and reload when a file is modified.

### CODE REVIEW

**Comment by kauffj** [comment]
What's the advantage to importing/exporting?

**Comment by alexliebowitz** [comment]
3 reasons:It makes the dependencies of each file clear and avoids having dozens of components and modules in global scope (which, while it's unlikely to actually cause problems in our case, is kinda ugly).

**Comment by alexliebowitz** [comment]
For one, ES6 modules don't even allow you to access global scope, so we don't have much of a choice if we're going to switch to modules. But there are also practical benefits: it makes the dependencies of each file clear and avoids having dozens of components and modules in global scope (which, while it's unlikely to actually cause problems in our case, is kinda ugly).

**Comment by alexliebowitz** [comment]
ES6 modules don't even allow you to access global scope, so we don't have much of a choice if we're going to switch to modules. But there are also practical benefits: it makes the dependencies of each file clear and avoids having dozens of components and modules in global scope (which, while it's unlikely to actually cause problems in our case, is kinda ugly).

**Pull request merged**
